// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using <%= name %>.Resources;
using <%= name %>.ViewControllers.iOS;
using <%= name %>.ViewModels;
using UIKit;

namespace <%= name %>.iOS
{
	public partial class MainViewController : BaseViewController<MainViewModel>
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
        }

        protected override void SetupControls()
        {
            base.SetupControls();
			HelloWorld.Text = Strings.HelloWorld;
		}
	}
}
